"""The agent surface — one URL to learn the API, one URL per answer.

Designed against a specific constraint: **many AI fetch tools cannot set HTTP
headers.** Claude Code's WebFetch cannot. An API that requires
`Authorization: Bearer` therefore excludes every agent that lacks a shell,
which is most of them. So reads accept `?key=`, and the cost — the key landing
in access logs — is paid only on the verb where it is survivable. The one write
here is header-only (see `security.require_agent_post`).

Responses are plain text by default because the caller is a language model, and
`?format=json` when something needs to parse. Both render from the identical
dict, so they cannot describe different states.

`/agent/help` is generated by walking this router's own routes rather than
written by hand. A hand-written manual is wrong the first time someone adds a
parameter and forgets the docs — and a confidently wrong manual is worse for an
agent than no manual, because it will follow it.
"""
from __future__ import annotations

import inspect

import fastapi.params
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.encoders import jsonable_encoder
from fastapi.responses import JSONResponse, PlainTextResponse
from fastapi.routing import APIRoute
from pydantic import BaseModel, Field
from slowapi import Limiter
from slowapi.util import get_remote_address

from ..db import conn, tx
from ..security import require_agent_post, require_agent_read
from ..services import agent as agent_svc
from ..services import drafts as drafts_svc

router = APIRouter()

# Per-router limiter, matching the pattern in routers/auth.py. Generous enough
# that no honest caller will notice, tight enough that a retry loop cannot use
# the box as a treadmill — every report below fans out into several queries.
_limiter = Limiter(key_func=get_remote_address)

_READ = Depends(require_agent_read)


def _respond(data: dict, text: str, fmt: str):
    """Text unless JSON was asked for. Same dict behind both."""
    if fmt == "json":
        return JSONResponse(jsonable_encoder(data))
    return PlainTextResponse(text + "\n")


# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------

_HELP_PREAMBLE = """\
CRAIGSLIST AUTO-POSTER — AGENT API

This system posts roofing ads to Craigslist from three rotating accounts, on a
schedule, with guardrails that cap how often each account may post. You are
talking to the dashboard that owns the queue and the history. The ads are
actually published by a Windows desktop that polls this server.

HOW TO CALL IT
  Every endpoint below is a GET unless marked otherwise. Add your key as
  `?key=<KEY>`, or send it as an `X-API-Key` header if you can set headers.
  Responses are plain English by default. Add `&format=json` if you need to
  parse one.

WHAT YOU CAN AND CANNOT DO
  Everything here is read-only except POST /agent/post-now, which publishes a
  draft you have already had a human approve. You cannot create drafts, write
  ad copy, change guardrails, edit live ads, or spend money on image
  generation. If you were asked to do one of those, say it is not available
  through this API rather than trying to find another route.

THREE THINGS THAT WILL MISLEAD YOU IF YOU DO NOT KNOW THEM
  1. View and impression counters come from a scrape that runs ONCE A DAY at
     06:00 Eastern on the posting desktop. They are never live. Today's numbers
     do not exist yet, and if that machine was off there is a gap.
  2. Post times are FORECASTS. They replay the posting rules against the
     current queue; a pause, a failure or an edit moves them.
  3. No errors does not mean healthy. Every error record has to be sent by a
     posting machine, so a machine that is switched off reports nothing at all
     and does no work. /agent/status lists when each machine last checked in.

WHEN SOMETHING LOOKS WRONG
  /agent/problems gives the ranked, explained view. /agent/logs gives the raw
  error records underneath it. Start with problems; go to logs when you need to
  know how often something happened.

ENDPOINTS
"""

_HELP_CLOSING = """\

EXAMPLES
  Is everything OK right now?
    {base}/agent/status?key=<KEY>
  How did we do last week?
    {base}/agent/stats?key=<KEY>&window=7d
  What is waiting to go out?
    {base}/agent/queue?key=<KEY>
  What broke, and what exactly did it say?
    {base}/agent/problems?key=<KEY>
    {base}/agent/logs?key=<KEY>&hours=48

  Publish a draft a human has already reviewed (needs a 'post'-scope key,
  and the key must be in a header — not the URL):
    curl -X POST {base}/agent/post-now \\
      -H "X-API-Key: <POST_KEY>" \\
      -H "Content-Type: application/json" \\
      -d '{{"draft_id": 123}}'
"""


def _describe_routes(base: str) -> str:
    """Build the endpoint list from the live route table.

    Uses each endpoint's own signature and docstring, so a parameter that
    exists is documented and one that does not cannot be.
    """
    blocks: list[str] = []
    for route in router.routes:
        if not isinstance(route, APIRoute) or route.path == "/help":
            continue
        method = "POST" if "POST" in route.methods else "GET"
        doc = inspect.getdoc(route.endpoint) or ""
        summary = doc.split("\n\n")[0].replace("\n", " ").strip()

        params: list[str] = []
        for name, param in inspect.signature(route.endpoint).parameters.items():
            default = param.default
            if not isinstance(default, fastapi.params.Query):
                continue
            description = getattr(default, "description", None) or ""
            fallback = getattr(default, "default", None)
            shown = "" if fallback in (None, Ellipsis) else f" (default: {fallback})"
            params.append(f"      {name}{shown} — {description}".rstrip(" —"))

        blocks.append(
            f"  {method} {base}/agent{route.path}\n"
            f"    {summary}"
            + ("\n    Parameters:\n" + "\n".join(params) if params else "")
        )
    return "\n\n".join(blocks)


@router.get("/help", response_class=PlainTextResponse)
@_limiter.limit("60/minute")
def help_page(request: Request, identity: dict = _READ):
    """Start here. Lists every question you can ask and how to ask it."""
    base = str(request.base_url).rstrip("/")
    body = (
        _HELP_PREAMBLE
        + _describe_routes(base)
        + "\n"
        + _HELP_CLOSING.format(base=base)
    )
    scope = identity["scope"]
    body += (
        "\nYOUR KEY\n"
        f"  Label: {identity['label'] or '(unlabelled)'} — scope: {scope}.\n"
        + (
            "  This key is read-only. POST /agent/post-now will refuse it.\n"
            if scope != "post"
            else "  This key may publish reviewed drafts via POST /agent/post-now.\n"
        )
    )
    return PlainTextResponse(body)


# ---------------------------------------------------------------------------
# Reads
# ---------------------------------------------------------------------------

@router.get("/status")
@_limiter.limit("60/minute")
def status_endpoint(
    request: Request,
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """Whether each account can post right now and why not, when the next post
    is due, how deep each queue is, and which machines are still reporting."""
    with conn() as c:
        data = agent_svc.status_report(c)
    return _respond(data, agent_svc.render_status(data), format)


@router.get("/queue")
@_limiter.limit("60/minute")
def queue_endpoint(
    request: Request,
    account: str | None = Query(default=None, description="restrict to one account"),
    reviewed: bool | None = Query(default=None, description="true to show only human-approved drafts"),
    limit: int = Query(default=20, ge=1, le=100, description="how many drafts to return"),
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """The drafts waiting to publish, what each is missing, and roughly when
    each one will go out."""
    with conn() as c:
        data = agent_svc.queue_report(
            c, account=account, reviewed=reviewed, limit=limit
        )
    return _respond(data, agent_svc.render_queue(data), format)


@router.get("/posts")
@_limiter.limit("60/minute")
def posts_endpoint(
    request: Request,
    account: str | None = Query(default=None, description="restrict to one account"),
    since: str = Query(default="30d", description="time window, e.g. 7d, 30d, 90d, or 'all'"),
    limit: int = Query(default=20, ge=1, le=100, description="how many posts to return"),
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """Ads that have published: whether each is still live, whether it is
    ghosted, and whether an edit is staged or has gone wrong."""
    with conn() as c:
        data = agent_svc.posts_report(c, account=account, since=since, limit=limit)
    return _respond(data, agent_svc.render_posts(data), format)


@router.get("/stats")
@_limiter.limit("60/minute")
def stats_endpoint(
    request: Request,
    window: str = Query(default="7d", description="'yesterday', '7d' or '30d'"),
    account: str | None = Query(default=None, description="restrict to one account"),
    limit: int = Query(default=20, ge=1, le=100, description="how many posts to list"),
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """Views and impressions earned during a period — a real difference between
    daily snapshots, not a lifetime average."""
    if window not in ("yesterday", "7d", "30d"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="window must be one of: yesterday, 7d, 30d",
        )
    with conn() as c:
        data = agent_svc.stats_report(c, window=window, account=account, limit=limit)
    return _respond(data, agent_svc.render_stats(data), format)


@router.get("/problems")
@_limiter.limit("60/minute")
def problems_endpoint(
    request: Request,
    hours: int = Query(default=72, ge=1, le=720, description="how far back to look"),
    limit: int = Query(default=30, ge=1, le=100, description="how many problems to return"),
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """What is currently wrong, ranked by severity, each with a plain-English
    explanation of what it means and where to fix it."""
    with conn() as c:
        data = agent_svc.problems_report(c, hours=hours, limit=limit)
    return _respond(data, agent_svc.render_problems(data), format)


@router.get("/logs")
@_limiter.limit("60/minute")
def logs_endpoint(
    request: Request,
    hours: int = Query(default=24, ge=1, le=720, description="how far back to look"),
    account: str | None = Query(default=None, description="restrict to one account"),
    flow: str | None = Query(default=None, description="restrict to one flow, e.g. post, edit, stats_sync"),
    limit: int = Query(default=40, ge=1, le=200, description="how many records to return"),
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """Raw error records exactly as the desktop reported them, newest first,
    undeduplicated — use this to see how often something is failing."""
    with conn() as c:
        data = agent_svc.logs_report(
            c, hours=hours, account=account, flow=flow, limit=limit
        )
    return _respond(data, agent_svc.render_logs(data), format)


@router.get("/inventory")
@_limiter.limit("60/minute")
def inventory_endpoint(
    request: Request,
    format: str = Query(default="text", description="'text' (default) or 'json'"),
    identity: dict = _READ,
):
    """How many images are available to fill upcoming posts, and how far short
    the photo and cover stacks are."""
    with conn() as c:
        data = agent_svc.inventory_report(c)
    return _respond(data, agent_svc.render_inventory(data), format)


# ---------------------------------------------------------------------------
# The one write
# ---------------------------------------------------------------------------

class PostNowBody(BaseModel):
    draft_id: int = Field(description="id of a queued, reviewed draft")


@router.post("/post-now", status_code=status.HTTP_202_ACCEPTED)
@_limiter.limit("10/minute")
def post_now_endpoint(
    request: Request,
    body: PostNowBody,
    identity: dict = Depends(require_agent_post),
):
    """Publish a draft a human has already reviewed. Requires a 'post'-scope key
    sent as a header."""
    with tx() as c:
        draft = drafts_svc.get_draft(c, body.draft_id)
        if draft is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"No draft with id {body.draft_id}.",
            )
        # The line an agent may not cross. Guardrails stop an account being
        # over-posted, but nothing else stops the wrong *words* going out under
        # this licence number and phone. A human reviewing the copy is the only
        # control there is, and it is not one this endpoint gets to skip.
        if not draft["reviewed"]:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=(
                    f"Draft {body.draft_id} has not been reviewed by a human. "
                    "Only reviewed drafts can be published through this API. "
                    "Ask the operator to review it in the dashboard first."
                ),
            )
        try:
            result = drafts_svc.request_post(
                c,
                body.draft_id,
                # Attribution, so a post that went out off-cadence can be
                # explained later. 'admin' would be a lie.
                requested_by=f"agent:{identity['label'] or identity['id']}",
            )
        except ValueError as e:
            raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(e))
        except drafts_svc.NotEligible as e:
            # Verbatim, and not retryable. These are the same strings the
            # dashboard and `cl status` print.
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail={
                    "message": f"{draft['account']} cannot post right now",
                    "reasons": e.reasons,
                    "advice": (
                        "This is a guardrail, not a transient error. Do not "
                        "retry — report these reasons to the user."
                    ),
                },
            )

    return {
        "requested": True,
        "draft_id": body.draft_id,
        "account": draft["account"],
        "title": draft["title"],
        "message": (
            "Request accepted. Nothing has published yet: the posting desktop "
            "picks this up on its next poll (~15 seconds) and then drives the "
            "Craigslist form. Check /agent/posts in a few minutes to confirm, "
            "and /agent/problems if it does not appear."
        ),
        "eligibility": jsonable_encoder(result.get("eligibility")),
    }
