"""let images be archived copies of what a posting already published

Revision ID: 0023
Revises: 0022
Create Date: 2026-08-02

A recovered posting's manifest holds Craigslist's own CDN URLs. Those resolve
today and carry no promise about tomorrow — they stop resolving when Craigslist
prunes the ad, which is exactly when somebody wants to see what was on it. So we
fetch the bytes and keep them ourselves, content-addressed like every other
image.

They need two values the existing CHECK constraints reject:

- `source = 'recovered'` — these were not generated by us and not uploaded by an
  operator. They came back off a posting we had already published.
- `status = 'archived'` — a terminal state the pickers ignore. `pick_for_draft`
  requires 'approved', so an archived row can never be handed to a new draft;
  that matters because these bytes have already been on Craigslist under one
  account, and reusing them elsewhere is the exact pattern decision 13 exists to
  prevent.
"""
from __future__ import annotations

from alembic import op

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_status_check;
        ALTER TABLE images ADD CONSTRAINT images_status_check
            CHECK (status IN ('pending','approved','rejected','test','archived'));

        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_source_check;
        ALTER TABLE images ADD CONSTRAINT images_source_check
            CHECK (source IN ('generated','uploaded','recovered'));
        """
    )


def downgrade() -> None:
    # Widening is safe to undo only if nothing used the new values; refuse
    # rather than silently delete somebody's only copy of a published picture.
    op.execute(
        """
        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_status_check;
        ALTER TABLE images ADD CONSTRAINT images_status_check
            CHECK (status IN ('pending','approved','rejected','test'));

        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_source_check;
        ALTER TABLE images ADD CONSTRAINT images_source_check
            CHECK (source IN ('generated','uploaded'));
        """
    )
