"""import photos from CompanyCam, and make the reuse rules tunable at runtime

Revision ID: 0027
Revises: 0026
Create Date: 2026-08-04

Three things, all in service of filling photo slots from real job-site pictures
instead of generated ones.

**`source = 'companycam'`.** These were neither generated by us, uploaded by
hand, nor recovered off a posting. The provenance matters: it is the only way to
tell later which pictures came out of the crews' own camera roll.

**Two rules stop being compiled constants.** `REUSE_COOLDOWN_DAYS` and the
permanent `owner_account` claim decided the size of the photo pool between them:
at ~166 photos a day, a 30-day cooldown needs ~4,980 standing photos, and the
per-account claim then splits that four ways. Moving to 7 days with no account
binding drops the requirement to ~1,160 shared across every account.

That is a real loosening of an anti-detection rule, so it lives in
`guardrail_settings` where it can be put back without a redeploy — the same
argument as `edits_enabled` in 0015. Craigslist ads run about 30 days, so a
7-day cooldown means the same photo is *expected* to be live under two accounts
at once. If posts start ghosting, `image_reuse_cooldown_days` and
`image_owner_binding` are the first two things to move, and moving them is an
UPDATE rather than a deploy.

`owner_account` values already written are deliberately left alone. They are
what makes the revert a real revert: flip `image_owner_binding` back on and the
old claims are still there to enforce.

**`image_sources` is an idempotency ledger**, keyed on the remote id rather than
on our `sha256`. It cannot be a column on `images`, because the relation is N→1:
crews photograph the same finished roof twice, two different CompanyCam ids
normalise to byte-identical JPEGs, `ON CONFLICT (sha256) DO NOTHING` writes no
second row, and there is nowhere to record that the second id was ever seen — so
every future run downloads it again, forever. A side table records the duplicate
pointing at the row that won. It also means the dedupe key does not depend on
Pillow encoding the same bytes across versions.
"""
from __future__ import annotations

from alembic import op

revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_source_check;
        ALTER TABLE images ADD CONSTRAINT images_source_check
            CHECK (source IN ('generated','uploaded','recovered','companycam'));

        ALTER TABLE guardrail_settings
            ADD COLUMN IF NOT EXISTS image_owner_binding       BOOLEAN NOT NULL DEFAULT FALSE,
            ADD COLUMN IF NOT EXISTS image_reuse_cooldown_days INTEGER NOT NULL DEFAULT 7;

        ALTER TABLE guardrail_settings
            DROP CONSTRAINT IF EXISTS guardrail_image_cooldown_range;
        ALTER TABLE guardrail_settings
            ADD CONSTRAINT guardrail_image_cooldown_range
            CHECK (image_reuse_cooldown_days BETWEEN 0 AND 365);

        CREATE TABLE IF NOT EXISTS image_sources (
            source        TEXT   NOT NULL,
            external_id   TEXT   NOT NULL,
            -- SET NULL rather than CASCADE: an operator hard-deleting a picture
            -- has made a decision, and dropping the ledger row would undo it by
            -- re-importing the same photo on the next run.
            image_id      BIGINT REFERENCES images(id) ON DELETE SET NULL,
            remote_hash   TEXT,
            remote_url    TEXT,
            sha256        TEXT,
            captured_at   TIMESTAMPTZ,
            project_id    TEXT,
            description   TEXT,
            state         TEXT NOT NULL DEFAULT 'imported',
            error         TEXT,
            attempts      INTEGER NOT NULL DEFAULT 0,
            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (source, external_id),
            CONSTRAINT image_sources_state_check
                CHECK (state IN ('imported','duplicate','failed','skipped'))
        );
        CREATE INDEX IF NOT EXISTS idx_image_sources_image
            ON image_sources(image_id);

        -- idx_images_pool (0005) is (status, owner_account, kind). With the
        -- owner predicate gone from pick_for_draft, Postgres can only use its
        -- `status` prefix, which selects most of the table. This restores an
        -- index the picker can actually walk.
        CREATE INDEX IF NOT EXISTS idx_images_pick ON images(kind, used_at)
            WHERE status = 'approved';
        """
    )


def downgrade() -> None:
    # Narrowing the CHECK would orphan every imported photo, so refuse while any
    # exist rather than making somebody's picture library unrepresentable. Same
    # reasoning as 0023.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM images WHERE source = 'companycam') THEN
                RAISE EXCEPTION
                    'images still carry source=companycam; re-source or delete '
                    'them before downgrading past 0027';
            END IF;
        END $$;

        DROP INDEX IF EXISTS idx_images_pick;
        DROP TABLE IF EXISTS image_sources;

        ALTER TABLE guardrail_settings
            DROP CONSTRAINT IF EXISTS guardrail_image_cooldown_range;
        ALTER TABLE guardrail_settings
            DROP COLUMN IF EXISTS image_reuse_cooldown_days,
            DROP COLUMN IF EXISTS image_owner_binding;

        ALTER TABLE images DROP CONSTRAINT IF EXISTS images_source_check;
        ALTER TABLE images ADD CONSTRAINT images_source_check
            CHECK (source IN ('generated','uploaded','recovered'));
        """
    )
